apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dir-rag-backend
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/cloudsql-instances: ""
    spec:
      containers:
        - image: asia-southeast2-docker.pkg.dev/PROJECT_ID/dir-rag-backend/dir-rag-backend:TAG
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: GOOGLE_CLOUD_PROJECT
              value: PROJECT_ID
          volumeMounts:
            - name: chroma-storage
              mountPath: /app/storage/vectors
      volumes:
        - name: chroma-storage
          cloudStorage:
            bucket: PROJECT_ID-chroma-vectors
            readOnly: false

